GET http://localhost:3001/api/persons/
###
GET http://localhost:3001/api/persons/1
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{       
  "name": "Adamseo", 
  "number": "39-44-5323523"
}
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{       
  "name": "Arto Hellas", 
  "number": "39-44-5323523"
}
###
DELETE http://localhost:3001/api/persons/1